### ISSUE TITLE
Fluidable child overflows when using spacing

### ISSUE THREAD

**Issue by talski** [andyduke/fluid_box#2]
with no spacing
![image](https://user-images.githubusercontent.com/740549/118039390-49a7a580-b33e-11eb-9a09-3d81eb4a7fb6.png)

with spacing: 16
![image](https://user-images.githubusercontent.com/740549/118039325-35fc3f00-b33e-11eb-89bd-6c34efb17cc3.png)

**Comment by andyduke** [comment]
@talski Please show the minimum code that reproduces this situation.

**Comment by talski** [comment]
Sure, here's it https://gist.github.com/talski/40cb8858ced983bfc9f4e716fa88b14b

**Comment by andyduke** [comment]
@talski I fixed the bug, you can update `fluid_box` to version **2.0.1** and check if everything works as you need.

**Comment by talski** [comment]
working fine now, thank you
