### ISSUE TITLE
Localization directionality support

### ISSUE THREAD

**Issue by SaudBako** [andyduke/fluid_box#4]
The layout does not respond to TextDirection.rtl.

**Comment by andyduke** [comment]
@SaudBako Do you mean the order of widgets nested in Fluid, or TextDirection within widgets nested in Fluid?

**Comment by SaudBako** [comment]
@andyduke The former. Widgets nested in Fluid are ordered from left to right despite the current directionality.

**Comment by ideaxenit** [comment]
@andyduke , is there any update on this?

**Comment by andyduke** [comment]
@SaudBako @ideaxenit Check out version [2.1.0](https://pub.dev/packages/fluid_kit/versions/2.1.0)
