### ISSUE TITLE
Spacing property causes wrapping regardless of min width

### ISSUE THREAD

**Issue by mi1971** [andyduke/fluid_box#5]
Hey, thanks for the widget, it is very useful. However adding spacing to the parent fluid seems to prevent side by side children regardless of their sizes. Everything wraps in all screen sizes.

**Comment by andyduke** [comment]
@mi1971 Could you provide a minimal code that reproduces this issue?

**Comment by mi1971** [comment]
Hey Andy, we can close this. Hard to reproduce, so must be something very specific to the inner content that I had inside the Fluidables. I can work around it with padding inside rather than spacing. Thank you.
