### ISSUE TITLE
Define which field to grow when it doesn't fit in a row

### ISSUE THREAD

**Issue by talski** [andyduke/fluid_box#6]
It would be nice to have a way to set which Fluidable will grow when they don't fit in a row.
```
As default, this:
| A | B | C | D|

will become this:
| A | B | C |
|     D     |

what to do if I want the first field to grow first?
|     A     |
| B | C | D |
```

**Comment by andyduke** [comment]
@talski This is impossible, since the current algorithm first determines how many widgets with their minimum width will fit in each row, and then distributes the row width between widgets in a row.
